---
- hosts: jenkins-master
  become: true 
  tasks: 
  - name: add jenkins key 
    rpm_key: 
      key:  https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      state: present 

  - name: add jenkins repo 
    yum_repository:
      name: jenkins
      baseurl: http://pkg.jenkins.io/redhat-stable
      description: Jenkins LTS Repository
      gpgcheck: yes

  - name: install java 
    dnf: 
      name: java-17-openjdk
      state: present

  - name: install fontconfig 
    dnf: 
      name: fontconfig
      state: present

  - name: install jenkins 
    dnf: 
      name: jenkins 
      state: present 

  - name: start jenkins service 
    service: 
      name: jenkins 
      state: started 

  - name: enable jenkins to start at boot time 
    service: 
      name: jenkins 
      enabled: yes 